M48
; DRILL file {KiCad 7.0.8} date 2024 February 15, Thursday 12:40:23
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-15T12:40:23+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X8.286Y-4.1579
X8.286Y-4.3854
X8.286Y-4.7087
X8.286Y-4.9362
T2
X3.822Y-5.4496
X7.324Y-3.5815
X8.3047Y-5.4496
T0
M30
